### ISSUE TITLE
Use older version of the U280 platform (xilinx_u280_xdma_201920_3)

### ISSUE THREAD

**Issue by EnXinY** [XACCNUS/Cluster#11]
Hi Hongshi,

I want to use older version of the U280 platform (xilinx_u280_xdma_201920_3), but the status of the "hacc-gpu1" node is always "mix" and I don't see any task occupying that node from sinfo. I hope you can give me some suggestions.

Thank you.

**Comment by HongshiTan** [comment]
Hi EnXinY,

The issue you are experiencing is due to the presence of other partitions that contain the hacc-gpu1 node, to which you currently do not have access permissions. 

As the hardware is shared among multiple public users, it is possible that another user may be utilizing the node at the same time. To ensure efficient use of the shared resources and avoid conflicts, I recommend using the "sbatch" command to submit your task script. This command will automatically queue your task and execute it once the other users release their allocations.
