### ISSUE TITLE
hacc-u280-4 with "No devices found"

### ISSUE THREAD

**Issue by EnXinY** [XACCNUS/Cluster#9]
Hi,

I get the following error when downloading a bitstream on U280 node.

![image](https://github.com/XACCNUS/User-Guide/assets/83993463/fe19655d-400c-478e-9e40-28e0b0ec4264)

And then xbutil validate failed too:

![image](https://github.com/XACCNUS/User-Guide/assets/83993463/9c71b69c-98ce-41fa-8c85-45369c8c9a0d)

I try dmesg and get the following message:

![image](https://github.com/XACCNUS/User-Guide/assets/83993463/6ec5cf3b-4457-4d44-aebe-727317e196aa)

Then I tried to hot reset the card using xbutil reset --device 0000:1b:00.1, but got the following warning:

![image](https://github.com/XACCNUS/User-Guide/assets/83993463/4cd5780b-e1f6-4428-aa6b-4663c720267a)

Can't find the device right now, I hope you can help me.

Thanks!

**Comment by HongshiTan** [comment]
Hi Xiny,

It should be a known issue for XRT drivers. Usually, if XRT tells you that you need to reset the board, rather than reset the board using XRT (xbutil reset), we would suggest you reboot the node with "sudo reboot" as we have given the user the authorization for rebooting the FPGA nodes.

Normally, the reboot will be finished in 5 min,  and after that, you can see it UP from sinfo. Then, you can validate the functionality using xbutil validate, and the FPGA should be recovered. If this still not working, you can let me know via email (hongshi@u.nus.edu)


Best regards,
Hongshi

**Comment by HongshiTan** [comment]
hacc-u280-4 has been recovered now

**Comment by EnXinY** [comment]
I test the download program and my problem is solved, thank you very much indeed.

**Comment by HongshiTan** [comment]
welcome
